name: Alex Burkhart
baseurl: "https://alexburkhart.com"
exclude: [
  .git,
  .gitignore,
  .DS_Store,
  CNAME,
  .sass-cache,
  Gemfile,
  Gemfile.lock,
  README.md,
  tmp
]
permalink: "/writing/:title"
excerpt_separator: "<!-- excerpt-end -->"
google_analytics_code: "UA-59756024-1"
defaults:
  -
    scope:
      path: "" # entire site
      type: "drafts"
    values:
      layout: "main"
  -
    scope:
      path: "" # entire site
      type: "posts"
    values:
      layout: "main"
